### ISSUE TITLE
Cannot find dependency luci-lua-runtime for luci-app-gpoint

### ISSUE THREAD

**Issue by jasongaunt** [Kodo-kakaku/luci-app-gpoint#10]
When installing on an x86_64 platform (admittedly I haven't tried this on any other platform) I get the following error;
```
root@OpenWRT:~# opkg install luci-app-gpoint_1.8.0_all.ipk
Unknown package 'luci-app-gpoint'.
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency luci-lua-runtime for luci-app-gpoint
 * pkg_hash_fetch_best_installation_candidate: Packages for luci-app-gpoint found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package luci-app-gpoint.
```

When attempting to install `luci-lua-runtime` no such package exists.

**Comment by Kodo-kakaku** [comment]
Hi! Tell me which version of OpenWRT are you using? Most likely the problem is with her. Have you tried installing any other packages for Luci, for example luci-app-uhttpd? Before that, I tested on x86 on OpenMPTCProuter and everything worked.

**Comment by jasongaunt** [comment]
Hi there,

OpenWRT 22.03 is what I have installed, and yes I have installed other packages such as to support QMI for the modem with the GPS receiver I wish to use (I can see NMEA strings if I `cat /dev/ttyUSB1`)

`OpenWrt 22.03.2 r19803-9a599fee93 / LuCI openwrt-22.03 branch git-22.288.45147-96ec0cd`

**Comment by Kodo-kakaku** [comment]
Hey, Jason!
Today I fixed the error of **OpenWRT support 22.3.2**. A new version 1.8.5 has been published, and you can try it in the work. I tested on Intel Celeron N2920. As soon as you test, write about the result, after that I will close issues. I will be waiting for your feedback!)

**Comment by jasongaunt** [comment]
Hi @Kodo-kakaku - that now works (amusing the location before it gets a fix 😂) thanks!

However there is a new issue - the sign (-) for Longitude is not being processed, it thinks my Longitude is "1.7xxxx" when it is "-1.7xxxx" and puts my location many miles away.

I checked the NMEA strings coming back and they are valid, this is a problem with gpoint, should I create a new issue for that?

**Comment by Kodo-kakaku** [comment]
I think I can fix it) I need NMEA data from your modem, coordinate data, you can specify the approximate main thing that they contain "-" so that I can check the correctness of the parsing. You don't need to create a new issue, as soon as I get the data from you, I'll do it right away, thank you!)

**Comment by jasongaunt** [comment]
@Kodo-kakaku Here you go:

```javascript
$GPGGA,215717.00,5129.118098,N,00134.841498,W,1,07,1.1,105.9,M,47.0,M,,*78
$GPVTG,178.9,T,183.1,M,0.0,N,0.0,K,A*2F
$GPGSA,A,2,08,10,16,18,23,26,27,,,,,,1.5,1.1,0.9*39
$GPGSV,6,1,22,07,20,302,25,08,43,284,30,10,39,133,32,15,07,042,23*70
$GPGSV,6,2,22,16,58,182,23,18,28,057,23,23,44,087,33,26,26,165,31*73
$GPGSV,6,3,22,27,80,299,29,13,04,015,,21,12,234,,30,07,333,*78
$GPGSV,6,4,22,33,,,35,38,,,35,39,,,34,41,,,34*7F
$GPGSV,6,5,22,42,,,35,46,,,34,48,,,35,49,,,34*7F
$GPGSV,6,6,22,50,,,35,51,,,35*78
```

**Comment by Kodo-kakaku** [comment]
Hello, @jasonfaunt!
I've done tests with your data, fixed the data transformation, and now everything should work)
I have made corrections to version 1.8.5 and re-released it. Unfortunately, I can use NMEA data emulation only for validation. I will be waiting for your feedback, it's important to me!

**Comment by jasongaunt** [comment]
@Kodo-kakaku You nailed it, it's working perfectly, thank you :)

**Comment by Kodo-kakaku** [comment]
Thank you for helping to identify the problems! Happy New Year!
