### ISSUE TITLE
Does not detect my modem

### ISSUE THREAD

**Issue by PR-NCE** [Kodo-kakaku/luci-app-gpoint#13]
it did not detect my modem, i looked into your code and my OpenWrt instance and realized that lsusb is not available on my OpenWrt, had to install usbutils to get it to recognize my modem, i think usbutils should be added to dependencies of your app.

**Comment by Kodo-kakaku** [comment]
Hi @PR-NCE ! You're right, this is my omission. I added the dependency to version 1.8.6 and now everything should work correctly. Thank you for your interest in the project, I am waiting for your feedback!

**Comment by PR-NCE** [comment]
Thank you Vladislav for your quick fix, I am really impressed with your project, after i got your app working i realized i didn't have a GPS antenna that could be connected to my modem, so now i have to order the antenna, when i get the antenna i will be able to use your app and provide more feedback.
