### ISSUE TITLE
Missing dependency for luci-compat

### ISSUE THREAD

**Issue by montaguethomas** [Kodo-kakaku/luci-app-gpoint#18]
The settings page has a dependency on the `luci-compat` package.

**Comment by Kodo-kakaku** [comment]
Hi @montaguethomas !
I understand this package is necessary for Lua compatibility on various platforms? Lack of compatibility caused by Lua version?
**Thank you for your interest in the project and your PR!**

**Comment by Kodo-kakaku** [comment]
Oh, I see now, thanks for the help!
