### ISSUE TITLE
Яндекс локатор

### ISSUE THREAD

**Issue by Maksibumdibum** [Kodo-kakaku/luci-app-gpoint#30]
Привет! У меня роутер ZBT-WE826T2 c модемом DW5821e. Поставили luci-app-gpoint и gpsd на openWRT. Через GPSD GPS работаем с сим-карты Мегафон, местоположение на улице определяет, все четко. 
Хочу попробовать Яндекс Локатор, чтобы он тоже определял местоположение. Получил пробное бесплатное API у Яндекса на 1000 запросов, ввел его API Key, сохранил, перезагрузил роутер. После перезагрузки в Service control пишется Yandex Locator: getting navigation data... Не получается получить местоположение... Предполагаю, что этому сервису что-то еще нужно, так как помимо ввода API Key есть еще Interface который предполагает выбор какого-то интерфейса wifi для Яндекс локатора. Но чтобы я не делал, выбор интерфейса мне не предоставляется, пишет всегда "Wifi not found".
Подскажи, пожалуйста, как это работает? Что мне сделать, чтобы получить местоположение по яндекс локатору?

**Comment by Kodo-kakaku** [comment]
Привет! Попробуйте выполнить команду iwinfo в терминале. Если она недоступна то попробуйте установить пакет iwinfo, это можно сделать командой:
`opkg update`
`opkg install iwinfo`

Надеюсь это Вам поможет, буду ждать от Вас обратной связи!

**Comment by Maksibumdibum** [comment]
Привет! Пакет есть, выполнилось. 
![Screenshot_4](https://github.com/user-attachments/assets/074506eb-d9c1-4d2a-9766-0a46d0a73ed1)
Но с яндекс локатором все так же, не выбора интерфейса wifi
![image](https://github.com/user-attachments/assets/4c32216b-13cf-4e14-bb02-ae173a1e4c10)
![image](https://github.com/user-attachments/assets/fb2da3a7-a1e1-457f-ae32-33474cfa8a1a)

**Comment by Kodo-kakaku** [comment]
Привет @Maksibumdibum !

**Comment by Maksibumdibum** [comment]
Привет, @Kodo-kakaku !
Спасибо большое, что пытаешься помочь мне)
После апдейта пишет, что нету версии 2.6.1
![Screenshot_20241007_123528_Browser](https://github.com/user-attachments/assets/77a35443-a7db-49ad-be39-cb0b4b1d7055)
![Screenshot_20241007_124143_Browser](https://github.com/user-attachments/assets/438f2d3d-5b96-463d-a094-49ee572a9c1d)

**Comment by Kodo-kakaku** [comment]
Привет @Maksibumdibum !
В скором времени репозиторий должен обновиться. Пока можно попробовать поставить gpoint локально, как это сделать подробно описано в readme, возможно потребуется удалить старую версию. Думаю это должно Вам помочь!

**Comment by Maksibumdibum** [comment]
Приветствую!
Большое Вам спасибо, сейчас поставил новую версию, интерфейс подгрузился и все заработало!!
